### ISSUE TITLE
Language selector

### ISSUE THREAD

**Issue by ludwich66** [840922704/BLE_DMM_Client#3]
great that you include a language selector. However, I would choose a variant with flags. If I choose Chinese as a European, I can't find anything anymore. the symbol is visually recognizable as language.
Of course I'm also looking forward to "German"

![image](https://user-images.githubusercontent.com/12202733/176666249-18b8b7da-9101-4f69-9c19-5e1390fd4ee7.png)

:-) ludwich

**Comment by 840922704** [comment]
The qt translator requests a translation file for each language. That means I need to change all the translation files once you change the layout content. (well... very similar to WordPress) This is the reason why I just added two languages by now.
I will look for a more practical implementation later.
