### ISSUE TITLE
BUGS

### ISSUE THREAD

**Issue by Kabron287** [840922704/BLE_DMM_Client#4]
1. Does not accept path manually
It always installed to C:\Program Files\BLE DMM Client\v3.1.0
2. Both Installer and portable connects to DMM but shows nothing.
![BUG](https://user-images.githubusercontent.com/2493191/187030052-af04329e-fe4f-44a0-adb9-57b9a2304363.jpg)

**Comment by 840922704** [comment]
1. Maybe it's a bug in the packer...
2. Press "Start" manually and it should work.

**Comment by 840922704** [comment]
Please try the new release V3.2.

**Comment by 840922704** [comment]
Closed due to no further reply.
